### PR TITLE
Fix ignoring of crispConfig.enableNotifications in ios

### LINKED ISSUE #125: [IOS] enableNotifications: false config option is ignored — notification permission prompt still appears
## Describe the bug

On iOS, when opening Crisp chat via `FlutterCrispChat.openCrispChat()` with `enableNotifications: false` in the config, the Crisp SDK still prompts the user to enable push notifications after sending the first message. The `enableNotifications` flag is silently ignored on iOS.

## To Reproduce

1. Integrate `crisp_chat: ^2.4.5` in a Flutter app
2. Call `FlutterCrispChat.openCrispChat()` with `enableNotifications: false`:

```dart
FlutterCrispChat.openCrispChat(
  config: CrispConfig(
    websiteID: 'your-website-id',
    enableNotifications: false,
  ),
);
```

3. Open the chat and send a message
4. **Observe**: iOS notification permission dialog appears despite `enableNotifications: false`

## Expected behavior

When `enableNotifications: false` is passed in `CrispConfig`, the Crisp SDK should not prompt the user for notification permissions. No push notification dialog should be shown.

## Smartphone

- **Device**: iPhone XR
- **OS**: iOS 17.7.1
- **Package version**: `crisp_chat ^2.4.5`
- **Flutter version**: 3.10.0+
- **Affects**: All iOS devices

## Root Cause

In `ios/Classes/SwiftFlutterCrispChatPlugin.swift`, the `enableNotifications` field is correctly parsed from the Flutter config into the native `CrispConfig` struct, but is **never passed to the Crisp iOS SDK**.

The `openCrispChat` handler calls `CrispSDK.configure(websiteID:)` but never calls `CrispSDK.setShouldPromptForNotificationPermission(_:)`:

```swift
// enableNotifications is parsed but never used
let crispConfig = CrispConfig.fromJson(args)

CrispSDK.configure(websiteID: websiteID)
// ❌ Missing: CrispSDK.setShouldPromptForNotificationPermission(crispConfig.enableNotifications)
```

The Crisp iOS SDK provides `setShouldPromptForNotificationPermission(_:)` specifically for this purpose. See: [Crisp iOS SDK Documentation](https://crisp-im.github.io/crisp-sdk-ios/documentation/crisp/crispsdk/setshouldpromptfornotificationpermission(_:)).

## Proposed Solution

Call `CrispSDK.setShouldPromptForNotificationPermission(_:)` after `CrispSDK.configure(websiteID:)`:

```swift
CrispSDK.configure(websiteID: websiteID)
CrispSDK.setShouldPromptForNotificationPermission(crispConfig.enableNotifications)
```

**Required changes:**
- File: `ios/Classes/SwiftFlutterCrispChatPlugin.swift`
- Location: After `CrispSDK.configure(websiteID: websiteID)` in the `openCrispChat` case
- Impact: +1 line of code

**Code diff:**

```diff
 CrispSDK.configure(websiteID: websiteID)
+CrispSDK.setShouldPromptForNotificationPermission(crispConfig.enableNotifications)
```

## Additional context

**Why this fix works:**
- `setShouldPromptForNotificationPermission(false)` tells the Crisp SDK not to request notification permissions from the user
- The `enableNotifications` field already exists in both the Dart `CrispConfig` class and the native Swift `CrispConfig` struct — only the forwarding call to the SDK is missing
- No breaking changes — `enableNotifications` defaults to `true`, preserving existing behavior

**References:**
- [Crisp iOS SDK — setShouldPromptForNotificationPermission](https://crisp-im.github.io/crisp-sdk-ios/documentation/crisp/crispsdk/setshouldpromptfornotificationpermission(_:))

### PR DESCRIPTION
**Pull request by aspid168**
Fix of [issue](https://github.com/alamin-karno/flutter-crisp-chat/issues/125)

### CODE REVIEW

File: ios/Classes/SwiftFlutterCrispChatPlugin.swift [hunk 1]
```diff
@@ -54,6 +54,7 @@ public class SwiftFlutterCrispChatPlugin: NSObject, FlutterPlugin, UIApplication
             }
 
             CrispSDK.configure(websiteID: websiteID)
+            CrispSDK.setShouldPromptForNotificationPermission(crispConfig.enableNotifications)
```
Comment (alamin-karno) [inline ios/Classes/SwiftFlutterCrispChatPlugin.swift:57]: Can you explain from where you find `setShouldPromptForNotificationPermission` function? I didn't find it any official documentation.

**Review by alamin-karno — CHANGES_REQUESTED** [review]

**Review by alamin-karno — APPROVED** [review]
Thanks, for you awesome support, @aspid168 .
